### ISSUE TITLE
Performance data improvement suggestions

### ISSUE THREAD

**Issue by jvandermeulen** [jonwitts/nagios-speedtest#2]
The Nagios Plugin Development Guidelines (https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT) inform us that a warning threshold configured as

> -w 35

means that any returned value **higher** than 35 wil issue a warning. For check_speedtest-cli.sh however lower values are worse than higher values. Officially (according to the plugin development guidelines) 
warning and critical thesholds for download should be configured like this:

> -w 35: -c 25:

The script fails with: 

> Download Warning Level with a value of: 35: is not a number!

and I can imagine that it will make it extra complex for relative new users of your plugin. So I can understand that the current situation is:

> -w 35 -c 25 

However it has a negative side affect on the gauge dashlets available in the commercial version of Nagios; Nagios XI. The current performance data for one of the data sources looks like this:

> |'download'=39.59;35;25 '

So the actual value is 39.59  (just on de safe side from warning and critical thresholds, respectively 35 and 25). The gauge looks like this:

![gauge-original](https://user-images.githubusercontent.com/838001/29894765-da491d12-8dd6-11e7-8655-930f3dc5d4ad.png)

A corrected version of an upload datasource (instead of download) with warning=25 and critical=10 may look like this:

> 'upload'=38.55;25:;10:;0;100

now the gauges shows this behaviour:
![gauge-corrected](https://user-images.githubusercontent.com/838001/29894918-753d649a-8dd7-11e7-81eb-546fff201bf0.png)

I intentionally made the maxiumum scale four times the warning threshold (4*25)
The code I used:

> 'upload'=$upload;$ULw:;$ULc:;0;$(echo $ULw*4|bc)"

So I suggest changing

> perfout="|'download'=$download;$DLw;$DLc 'upload'=$upload;$ULw;$ULc"

to

> perfout="|'download'=$download;$DLw:;$DLc:;0;$(echo $DLw*4|bc) 'upload'=$upload;$ULw:;$ULc:;0;$(echo $ULw*4|bc)"
![gauge](https://user-images.githubusercontent.com/838001/29895506-9e0bbc9e-8dd9-11e7-93bd-a2a0a0c1e59f.png)

Please let me know your feedback on this.

**Comment by jonwitts** [comment]
I see what you have done there Jorgen... It took me a little while to see how adding the maximum was resolving the dial issue. I like it; it's simple and should work for all uses of the perf data. I am going to add that change today and will run it on my nagiosgraph install to check it out.

Thanks again for contributing.

Jon

**Comment by jonwitts** [comment]
Multiplying the warning threshold by 4 was not enough for it to be greater than the maximum available upload and download amounts at my workplace, so I am going to adjust it so that if you request perfdata output, you must also provide maximum upload and download levels to the script. I will then add 5% to the provided figures for the perfdata maximum level./
