### ISSUE TITLE
problem with nagios-speedtest script

### ISSUE THREAD

**Issue by SistemasEnergy** [jonwitts/nagios-speedtest#3]
Hi all,

I have installed speedtest-cli script and I get this error

> You do not have the expected number of indices in your output from SpeedTest. Is it correctly installed? Try running the check with the -V argument to see what is going wrong.

What should I do to fix that?

Thanks in advance and regards

**Comment by jonwitts** [comment]
Have you run the check on the command line with the -V argument? What output does that give you?

**Comment by SistemasEnergy** [comment]
How can I check that? If I put the command 

`./check_speedtest-cli.sh` -V

only appears the help. 
Sorry but I'm so noob with Linux.

Regards

**Comment by jonwitts** [comment]
What have you put for your command definition in Nagios?

**Comment by SistemasEnergy** [comment]
I have this:
![imagen](https://user-images.githubusercontent.com/36956897/41703016-49ea472a-7532-11e8-8c07-0dd033cbd31e.png)

**Comment by jonwitts** [comment]
So add the -V to the command line definition and then see what is returned... Do you have command line access to teh server instead of this web based access?

**Comment by SistemasEnergy** [comment]
Yes, I can access the server via SSH, how will be the complete command to check that?

**Comment by jonwitts** [comment]
So you need to be in the directory that contains your check_speedtest-cli.sh file and then run the command as you see it in your screen grab, replacing your ARGS with the values you are using and then also including the -V argument on the end...

**Comment by SistemasEnergy** [comment]
Hi, if I try to run it, I get this result:

![imagen](https://user-images.githubusercontent.com/36956897/41849801-95e35f9c-7882-11e8-94e5-26f4aea6813c.png)

**Comment by jonwitts** [comment]
Can you show me what you have defined on line 175 of your check_speedtest.sh file please?

**Comment by SistemasEnergy** [comment]
Hi, I have this on the script which is placed on directory /usr/lib/centreon/plugins:
 STb=”/usr/bin”

**Comment by jonwitts** [comment]
Remove the quotation marks around /usr/bin and it should work.

**Comment by SistemasEnergy** [comment]
Now is working, thank you so much Jon!

Regards

**Comment by jonwitts** [comment]
No worries. Glad you got it going!
