### ISSUE TITLE
-p option & nagiosgraphs

### ISSUE THREAD

**Issue by defactocth** [jonwitts/nagios-speedtest#7]
Hi,

Thanks for the very useful plugin.

I am having trouble wiht the -p option breaking the script both on the command line and when used in a nagios service both work without the  -p though.

I have also setup a fresh install of nagiosgraph and it sees all the other service checks on the host bar this one... would this have something to do with not using the -p?

I'm using ubuntu 18.04.3

Any help would be most appreiciated.

Thanks.

**Comment by jonwitts** [comment]
Well the -p option is what outputs the performance data... Any services that don't output perf data won't output anything in nagiosgraph...

What is the error message you are getting when you add the -p option?

Can you copy and paste everything you are seeing here?

**Comment by defactocth** [comment]
Hi,

Appologies on the delay in getting back to you.

Without the -p the result is
`./check_speedtest-cli.sh -w 70 -c 40 -W 3 -C 1 -l e -s 8713
OK - Ping = 10.414 ms Download = 92.77 Mbit/s Upload = 3.99 Mbit/s
`
With the -p
`./check_speedtest-cli.sh -w 70 -c 40 -W 3 -C 1 -l e -s 8713 -p
        ******************************************************************************************

        Nagios speedtest-cli plugin - Version: 1.2 2017122011:01

        OPTIONS:
        -h      Show this message
        -w      Download Warning Level - *Required* - integer or floating point
        -c      Download Critical Level - *Required* - integer or floating point
        -W      Upload Warning Level - *Required* - integer or floating point
        -C      Upload Critical Level - *Required* - integer or floating point
        -l      Location of speedtest server - *Required * - takes either "i" or "e". If you pass "i" for
                Internal then you will need to pass the URL of the Mini Server to the "s" option. If you pass
                "e" for External then you must pass the server integer to the "s" option.
        -s      Server integer or URL for the speedtest server to test against - *Required* - Run
                "speedtest --list | less" to find your nearest server and note the number of the server
                or use the URL of an internal Speedtest Mini Server
        -p      Output Performance Data
        -m      Download Maximum Level - *Required if you request perfdata* - integer or floating point
                Provide the maximum possible download level in Mbit/s for your connection
        -M      Upload Maximum Level - *Required if you request perfdata* - integer or floating point
                Provide the maximum possible upload level in Mbit/s for your connection
        -v      Output plugin version
        -V      Output debug info for testing

        This script will output the Internet Connection Speed using speedtest-cli to Nagios.

        You need to have installed speedtest-cli on your system first and ensured that it is
        working by calling "speedtest --simple".

        See here: https://github.com/sivel/speedtest-cli for info about speedtest-cli

        First you MUST define the location of your speedtest install in the script or this will
        not work.

        The speedtest-cli can take some time to return its result. I recommend that you set the
        service_check_timeout value in your main nagios.cfg  to 120 to allow time for
        this script to run; but test yourself and adjust accordingly.

        You also need to have access to bc on your system for this script to work and that it
        exists in your path.

        Your warning levels must be higher than your critical levels for both upload and download.

        Performance Data will output upload and download speed against matching warning and
        critical levels.

        Jon Witts

        ******************************************************************************************
`

**Comment by jonwitts** [comment]
I see now...

You must provide -m and -M if you are requesting perfdata...

        -p      Output Performance Data
        -m      Download Maximum Level - *Required if you request perfdata* - integer or floating point
                Provide the maximum possible download level in Mbit/s for your connection
        -M      Upload Maximum Level - *Required if you request perfdata* - integer or floating point
                Provide the maximum possible upload level in Mbit/s for your connection

This is so that the perfdata can draw the graphs the correct way...

Try this for your command:

        ./check_speedtest-cli.sh -w 70 -c 40 -W 3 -C 1 -l e -s 8713 -p -m 100 -M 5

Jon

**Comment by defactocth** [comment]
Hi Jon,

I have tried your suggestion and it works great now.

Appologies I should have read the switch options more carefully.

Thanks for your help.

**Comment by jonwitts** [comment]
Not a problem. Glad you have it all going now.
